name: auto-bot-public

on:
  schedule:
    - cron: '00 6 * * *'  # Runs at 0t:00 GMT every day
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  run-daily-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Run ETL script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH }}
        FROM_WHATSAPP: ${{ secrets.FROM_WHATSAPP }}
        TO_WHATSAPP: ${{ secrets.TO_WHATSAPP }}
      run: |
        python3 auto-bot.py
